version: "3.7"

services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: rails

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - rails

