version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
     - '3000:3000'
    volumes:
      - ../:/usr/src/app
    command: "tail -f /dev/null"
